# Generated by Django 4.0 on 2021-12-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_date_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
